/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocumentsOficiosRouteImport } from './routes/documents.oficios'
import { Route as DocumentsMinutasRouteImport } from './routes/documents.minutas'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsOficiosRoute = DocumentsOficiosRouteImport.update({
  id: '/documents/oficios',
  path: '/documents/oficios',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsMinutasRoute = DocumentsMinutasRouteImport.update({
  id: '/documents/minutas',
  path: '/documents/minutas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/graph': typeof GraphRoute
  '/issues': typeof IssuesRoute
  '/login': typeof LoginRoute
  '/documents/minutas': typeof DocumentsMinutasRoute
  '/documents/oficios': typeof DocumentsOficiosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/graph': typeof GraphRoute
  '/issues': typeof IssuesRoute
  '/login': typeof LoginRoute
  '/documents/minutas': typeof DocumentsMinutasRoute
  '/documents/oficios': typeof DocumentsOficiosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/graph': typeof GraphRoute
  '/issues': typeof IssuesRoute
  '/login': typeof LoginRoute
  '/documents/minutas': typeof DocumentsMinutasRoute
  '/documents/oficios': typeof DocumentsOficiosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/graph'
    | '/issues'
    | '/login'
    | '/documents/minutas'
    | '/documents/oficios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/graph'
    | '/issues'
    | '/login'
    | '/documents/minutas'
    | '/documents/oficios'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/graph'
    | '/issues'
    | '/login'
    | '/documents/minutas'
    | '/documents/oficios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  GraphRoute: typeof GraphRoute
  IssuesRoute: typeof IssuesRoute
  LoginRoute: typeof LoginRoute
  DocumentsMinutasRoute: typeof DocumentsMinutasRoute
  DocumentsOficiosRoute: typeof DocumentsOficiosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/oficios': {
      id: '/documents/oficios'
      path: '/documents/oficios'
      fullPath: '/documents/oficios'
      preLoaderRoute: typeof DocumentsOficiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/minutas': {
      id: '/documents/minutas'
      path: '/documents/minutas'
      fullPath: '/documents/minutas'
      preLoaderRoute: typeof DocumentsMinutasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  GraphRoute: GraphRoute,
  IssuesRoute: IssuesRoute,
  LoginRoute: LoginRoute,
  DocumentsMinutasRoute: DocumentsMinutasRoute,
  DocumentsOficiosRoute: DocumentsOficiosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
